//! Phase 7: Integration Tests for Planning Service and File I/O
//!
//! This module provides integration tests that verify the interaction
//! between multiple components of the system.

use std::fs;
use std::path::{Path, PathBuf};
use tempfile::TempDir;

use xzagentz::domain::planning::{
    ArchitectureDocument, ArchitectureParser, Component, Phase, PlanGenerator, PlanMetadata,
    PlanOptions, PlanWriter, Requirement, Section, Task,
};
use xzagentz::infrastructure::fileio::{MarkdownArchitectureParser, MarkdownPlanWriter};

// ============================================================================
// Mock Implementations for Testing
// ============================================================================

struct MockPlanGenerator {
    should_fail: bool,
}

impl MockPlanGenerator {
    fn new() -> Self {
        Self { should_fail: false }
    }

    fn with_failure() -> Self {
        Self { should_fail: true }
    }
}

impl PlanGenerator for MockPlanGenerator {
    type Error = std::io::Error;

    fn generate_plan(
        &self,
        _arch: &ArchitectureDocument,
        _options: &PlanOptions,
    ) -> Result<xzagentz::domain::planning::Plan, Self::Error> {
        if self.should_fail {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                "Mock generation failed",
            ));
        }

        let metadata =
            PlanMetadata::new(chrono::Utc::now(), "mock-model", PathBuf::from("test.md"));

        let task1 = Task::new("Setup infrastructure", "Configure the infrastructure")
            .with_acceptance_criteria(vec!["Infrastructure configured".to_string()])
            .with_components(vec!["Infrastructure".to_string()]);

        let phase1 = Phase::new("phase-1", "Infrastructure Setup", "Setup infrastructure")
            .with_tasks(vec![task1])
            .with_estimated_duration("1 week");

        let task2 = Task::new("Implement features", "Build core features")
            .with_acceptance_criteria(vec!["Features implemented".to_string()])
            .with_components(vec!["Core".to_string()]);

        let phase2 = Phase::new("phase-2", "Feature Development", "Develop features")
            .with_tasks(vec![task2])
            .with_estimated_duration("2 weeks");

        Ok(xzagentz::domain::planning::Plan::new(
            "Mock Implementation Plan",
            "Generated by mock",
            vec![phase1, phase2],
            metadata,
        ))
    }
}

struct MockArchitectureParser {
    should_fail: bool,
}

impl MockArchitectureParser {
    fn new() -> Self {
        Self { should_fail: false }
    }

    fn with_failure() -> Self {
        Self { should_fail: true }
    }
}

impl ArchitectureParser for MockArchitectureParser {
    type Error = std::io::Error;

    fn parse(&self, _content: &str) -> Result<ArchitectureDocument, Self::Error> {
        if self.should_fail {
            return Err(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Mock parse failed",
            ));
        }

        let mut doc = ArchitectureDocument::new("Mock Architecture")
            .with_description("A mock architecture document");

        let section = Section::new("Overview", 1).with_content("Mock overview content");
        doc.add_section(section);

        let component = Component::new("MockComponent", "mock-comp")
            .with_description("A mock component")
            .with_technology("Service");
        doc.add_component(component);

        let requirement = Requirement::new("REQ-001", "Mock requirement")
            .with_priority("High")
            .with_category("Functional");
        doc.add_requirement(requirement);

        Ok(doc)
    }
}

struct MockPlanWriter {
    should_fail: bool,
}

impl MockPlanWriter {
    fn new() -> Self {
        Self { should_fail: false }
    }

    fn with_failure() -> Self {
        Self { should_fail: true }
    }
}

impl PlanWriter for MockPlanWriter {
    type Error = std::io::Error;

    fn write_plan(
        &self,
        _plan: &xzagentz::domain::planning::Plan,
        _output_path: &Path,
    ) -> Result<(), Self::Error> {
        if self.should_fail {
            return Err(std::io::Error::new(
                std::io::ErrorKind::PermissionDenied,
                "Mock write failed",
            ));
        }
        Ok(())
    }
}

// Wrapper for MockArchitectureParser that reads files
struct MockFileParser {
    inner: MockArchitectureParser,
}

impl MockFileParser {
    fn new() -> Self {
        Self {
            inner: MockArchitectureParser::new(),
        }
    }

    fn with_failure() -> Self {
        Self {
            inner: MockArchitectureParser::with_failure(),
        }
    }

    fn parse_file(&self, path: &Path) -> Result<ArchitectureDocument, std::io::Error> {
        let content = fs::read_to_string(path)?;
        self.inner.parse(&content)
    }
}

// ============================================================================
// Planning Service Integration Tests
// ============================================================================

#[test]
fn test_planning_service_successful_workflow() {
    let generator = MockPlanGenerator::new();
    let parser = MockFileParser::new();
    let _writer = MockPlanWriter::new();

    let temp_dir = TempDir::new().unwrap();
    let arch_path = temp_dir.path().join("architecture.md");
    fs::write(&arch_path, "# Test Architecture\n\nContent").unwrap();

    let arch_doc = parser.parse_file(&arch_path).unwrap();
    let options = PlanOptions::default();
    let result = generator.generate_plan(&arch_doc, &options);

    assert!(result.is_ok());
    let plan = result.unwrap();
    assert_eq!(plan.title(), "Mock Implementation Plan");
    assert_eq!(plan.phases().len(), 2);
}

#[test]
fn test_planning_service_parser_failure() {
    let parser = MockFileParser::with_failure();

    let temp_dir = TempDir::new().unwrap();
    let arch_path = temp_dir.path().join("architecture.md");
    fs::write(&arch_path, "# Test\n\nContent").unwrap();

    let result = parser.parse_file(&arch_path);
    assert!(result.is_err());
}

#[test]
fn test_planning_service_generator_failure() {
    let generator = MockPlanGenerator::with_failure();
    let parser = MockArchitectureParser::new();

    let arch_doc = parser.parse("# Test Architecture").unwrap();
    let options = PlanOptions::default();
    let result = generator.generate_plan(&arch_doc, &options);

    assert!(result.is_err());
}

#[test]
fn test_planning_service_save_plan_success() {
    let writer = MockPlanWriter::new();

    let metadata = PlanMetadata::new(chrono::Utc::now(), "test-model", PathBuf::from("test.md"));
    let plan = xzagentz::domain::planning::Plan::new("Test Plan", "Description", vec![], metadata);

    let temp_dir = TempDir::new().unwrap();
    let output_path = temp_dir.path().join("plan.md");

    let result = writer.write_plan(&plan, &output_path);
    assert!(result.is_ok());
}

#[test]
fn test_planning_service_save_plan_failure() {
    let writer = MockPlanWriter::with_failure();

    let metadata = PlanMetadata::new(chrono::Utc::now(), "test-model", PathBuf::from("test.md"));
    let plan = xzagentz::domain::planning::Plan::new("Test Plan", "Description", vec![], metadata);

    let temp_dir = TempDir::new().unwrap();
    let output_path = temp_dir.path().join("plan.md");

    let result = writer.write_plan(&plan, &output_path);
    assert!(result.is_err());
}

// ============================================================================
// Real File I/O Integration Tests
// ============================================================================

#[test]
fn test_real_markdown_parser_with_valid_file() {
    let parser = MarkdownArchitectureParser::new();

    let content = r#"# Test Architecture

## Overview

This is a test architecture document.

## Components

- Component A: Handles data processing
- Component B: Manages user interface

## Requirements

- REQ-001: System must be scalable
- REQ-002: System must be secure
"#;

    let result = parser.parse(content);
    assert!(result.is_ok());

    let doc = result.unwrap();
    assert_eq!(doc.title(), "Test Architecture");
}

#[test]
fn test_real_markdown_parser_with_empty_content() {
    let parser = MarkdownArchitectureParser::new();
    let result = parser.parse("");

    // Should handle empty content gracefully
    assert!(result.is_ok() || result.is_err());
}

#[test]
fn test_real_markdown_writer_with_valid_plan() {
    let writer = MarkdownPlanWriter::new();

    let metadata = PlanMetadata::new(chrono::Utc::now(), "test-model", PathBuf::from("test.md"));

    let task = Task::new("Test Task", "Task description")
        .with_acceptance_criteria(vec!["Criterion 1".to_string()])
        .with_components(vec!["Component 1".to_string()]);

    let phase = Phase::new("phase-1", "Test Phase", "Phase description")
        .with_tasks(vec![task])
        .with_estimated_duration("1 week");

    let plan = xzagentz::domain::planning::Plan::new(
        "Test Plan",
        "Plan description",
        vec![phase],
        metadata,
    );

    let temp_dir = TempDir::new().unwrap();
    let output_path = temp_dir.path().join("output_plan.md");

    let result = writer.write_plan(&plan, &output_path);
    assert!(result.is_ok());

    // Verify file was created
    assert!(output_path.exists());

    // Verify file content
    let content = fs::read_to_string(&output_path).unwrap();
    assert!(content.contains("Test Plan"));
    assert!(content.contains("Test Phase"));
    assert!(content.contains("Test Task"));
}

#[test]
fn test_real_markdown_writer_with_invalid_path() {
    let writer = MarkdownPlanWriter::new();

    let metadata = PlanMetadata::new(chrono::Utc::now(), "test-model", PathBuf::from("test.md"));
    let plan = xzagentz::domain::planning::Plan::new("Test Plan", "Description", vec![], metadata);

    let invalid_path = PathBuf::from("/nonexistent/directory/plan.md");
    let result = writer.write_plan(&plan, &invalid_path);

    assert!(result.is_err());
}

// ============================================================================
// End-to-End Integration Tests
// ============================================================================

#[test]
fn test_end_to_end_plan_generation_with_real_components() {
    let parser = MarkdownArchitectureParser::new();
    let generator = MockPlanGenerator::new();
    let writer = MarkdownPlanWriter::new();

    let arch_content = r#"# Microservices Architecture

## Overview

A scalable microservices architecture for handling high-volume traffic.

## Components

### API Gateway
Entry point for all client requests.

### Authentication Service
Handles user authentication and authorization.

### Data Processing Service
Processes incoming data streams.

## Requirements

- REQ-001: Support 10,000 concurrent users
- REQ-002: 99.9% uptime SLA
- REQ-003: Data encryption at rest and in transit
"#;

    let arch_doc = parser.parse(arch_content).unwrap();

    // Generate plan
    let options = PlanOptions::default().with_num_phases(3);
    let result = generator.generate_plan(&arch_doc, &options);
    assert!(result.is_ok());

    let plan = result.unwrap();
    assert!(!plan.phases().is_empty());

    // Save plan
    let temp_dir = TempDir::new().unwrap();
    let output_path = temp_dir.path().join("implementation_plan.md");
    let save_result = writer.write_plan(&plan, &output_path);
    assert!(save_result.is_ok());

    // Verify output file
    assert!(output_path.exists());
    let content = fs::read_to_string(&output_path).unwrap();
    assert!(content.contains("Implementation Plan"));
}

#[test]
fn test_plan_generation_with_options() {
    let generator = MockPlanGenerator::new();
    let parser = MockArchitectureParser::new();

    let arch_doc = parser.parse("# Test Architecture\n\nContent").unwrap();

    let options = PlanOptions::default()
        .with_num_phases(5)
        .with_model("custom-model")
        .with_temperature(0.8)
        .with_max_tokens(4000);

    let result = generator.generate_plan(&arch_doc, &options);
    assert!(result.is_ok());

    let plan = result.unwrap();
    assert!(!plan.phases().is_empty());
}

#[test]
fn test_multiple_plan_generations() {
    let generator = MockPlanGenerator::new();
    let parser = MockArchitectureParser::new();
    let writer = MarkdownPlanWriter::new();

    let arch_doc = parser.parse("# Test Architecture\n\nContent").unwrap();

    let temp_dir = TempDir::new().unwrap();

    for i in 0..5 {
        let output_path = temp_dir.path().join(format!("plan_{}.md", i));
        let options = PlanOptions::default();

        let result = generator.generate_plan(&arch_doc, &options);
        assert!(result.is_ok());

        let plan = result.unwrap();
        let save_result = writer.write_plan(&plan, &output_path);
        assert!(save_result.is_ok());
        assert!(output_path.exists());
    }
}

// ============================================================================
// Error Handling Integration Tests
// ============================================================================

#[test]
fn test_error_propagation_from_parser() {
    let parser = MockArchitectureParser::with_failure();

    let result = parser.parse("test content");
    assert!(result.is_err());

    let error_message = result.unwrap_err().to_string();
    assert!(error_message.contains("Mock"));
}

#[test]
fn test_error_propagation_from_generator() {
    let generator = MockPlanGenerator::with_failure();
    let parser = MockArchitectureParser::new();

    let arch_doc = parser.parse("# Test\n\nContent").unwrap();

    let options = PlanOptions::default();
    let result = generator.generate_plan(&arch_doc, &options);

    assert!(result.is_err());
}

#[test]
fn test_error_propagation_from_writer() {
    let writer = MockPlanWriter::with_failure();

    let metadata = PlanMetadata::new(chrono::Utc::now(), "test-model", PathBuf::from("test.md"));
    let plan = xzagentz::domain::planning::Plan::new("Test Plan", "Description", vec![], metadata);

    let output_path = PathBuf::from("output.md");
    let result = writer.write_plan(&plan, &output_path);

    assert!(result.is_err());
}
